name: Build e Deploy para GitHub Pages

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Build do App-React
        working-directory: app-react
        run: |
          echo "Instalação dependencias e Build aplicação REACT..."
          npm install
          npm run build

      - name: Deploy para GitHub-Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: app-react/build
          branch: gh-pages
