# Action para linter e testes de Integração
name: Testes de Integração
on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v5
